prometheus:
  prometheusSpec:
    retention: 7d
grafana:
  grafana.ini:
    server:
      root_url: http://localhost/grafana
      domain: localhost
      serve_from_sub_path: true
  ingress:
    enabled: true
    hosts:
      - localhost
